import styled from 'styled-components';
export const StyledToolbar = styled.div`
  max-height: 44px;
  min-height: 44px;
  position: relative;
  z-index: 7;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  left: 0;
  right: 8px;
  top: 0;
  font-size: inherit;
  white-space: nowrap;
  padding-left: 12px;
  background: var(--colors-background-default);
  background-color: white;
  font-family: var(--font-family-body);
  font-weight: 400;
  border-bottom: #c2c5c8 1px solid;
`;
