/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DataRouteRouteImport } from './routes/_data/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DataIndexRouteImport } from './routes/_data/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DataNaniesIndexRouteImport } from './routes/_data/nanies/index'
import { Route as DataMaidsIndexRouteImport } from './routes/_data/maids/index'
import { Route as DataDriversIndexRouteImport } from './routes/_data/drivers/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRouteRoute = DataRouteRouteImport.update({
  id: '/_data',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DataNaniesIndexRoute = DataNaniesIndexRouteImport.update({
  id: '/nanies/',
  path: '/nanies/',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataMaidsIndexRoute = DataMaidsIndexRouteImport.update({
  id: '/maids/',
  path: '/maids/',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataDriversIndexRoute = DataDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => DataRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DataIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/': typeof AuthIndexRoute
  '/drivers/': typeof DataDriversIndexRoute
  '/maids/': typeof DataMaidsIndexRoute
  '/nanies/': typeof DataNaniesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof DataIndexRoute
  '/auth': typeof AuthIndexRoute
  '/drivers': typeof DataDriversIndexRoute
  '/maids': typeof DataMaidsIndexRoute
  '/nanies': typeof DataNaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_data': typeof DataRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/_data/': typeof DataIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_data/drivers/': typeof DataDriversIndexRoute
  '/_data/maids/': typeof DataMaidsIndexRoute
  '/_data/nanies/': typeof DataNaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/auth/login'
    | '/auth/'
    | '/drivers/'
    | '/maids/'
    | '/nanies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth/login'
    | '/'
    | '/auth'
    | '/drivers'
    | '/maids'
    | '/nanies'
  id:
    | '__root__'
    | '/_data'
    | '/auth'
    | '/about'
    | '/auth/login'
    | '/_data/'
    | '/auth/'
    | '/_data/drivers/'
    | '/_data/maids/'
    | '/_data/nanies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DataRouteRoute: typeof DataRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_data': {
      id: '/_data'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DataRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_data/': {
      id: '/_data/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_data/nanies/': {
      id: '/_data/nanies/'
      path: '/nanies'
      fullPath: '/nanies/'
      preLoaderRoute: typeof DataNaniesIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/_data/maids/': {
      id: '/_data/maids/'
      path: '/maids'
      fullPath: '/maids/'
      preLoaderRoute: typeof DataMaidsIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/_data/drivers/': {
      id: '/_data/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DataDriversIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
  }
}

interface DataRouteRouteChildren {
  DataIndexRoute: typeof DataIndexRoute
  DataDriversIndexRoute: typeof DataDriversIndexRoute
  DataMaidsIndexRoute: typeof DataMaidsIndexRoute
  DataNaniesIndexRoute: typeof DataNaniesIndexRoute
}

const DataRouteRouteChildren: DataRouteRouteChildren = {
  DataIndexRoute: DataIndexRoute,
  DataDriversIndexRoute: DataDriversIndexRoute,
  DataMaidsIndexRoute: DataMaidsIndexRoute,
  DataNaniesIndexRoute: DataNaniesIndexRoute,
}

const DataRouteRouteWithChildren = DataRouteRoute._addFileChildren(
  DataRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DataRouteRoute: DataRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
